saml_metadata:
  path:     /saml/metadata
  defaults: { _controller: seb_saml.controller::metadataAction }

saml_acs:
  path:     /saml/acs
  methods:  ['POST']
  defaults: { _controller: seb_saml.controller::assertionConsumerServiceAction }

saml_login:
  path:     /saml/login
  defaults: { _controller: seb_saml.controller::loginAction }

saml_logout:
  path:     /saml/logout
  defaults: { _controller: seb_saml.controller::singleLogoutServiceAction }
